apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web-ui
  template:
    metadata:
      labels:
        component: web-ui
    spec:
      containers:
        - name: web-ui
          