apiVersion: v1
kind: ConfigMap
metadata:
  name: global-configmap
data:
  NGINX_PORT: "80"
  GRAFANA_PORT: "3000"
  FORECAST_SERVICE_PORT: "4242"
  TRAINING_SERVICE_PORT: "4243"
  MLFLOW_PORT: "5050"
  POSTGRES_PORT: "5432"
  RAY_HEAD_PORT: "6379"
  RAY_METRICS_EXPORT_PORT: "6565"
  RAY_DASHBOARD_PORT: "8265"
  RAY_CLIENT_SERVER_PORT: "10001"
  WEB_UI_PORT: "8000"
  AIRFLOW_WEBSERVER_PORT: "8080"
  KAFKA_UI_PORT: "8800"
  CADVISOR_PORT: "8089"
  PROMETHEUS_PORT: "9090"
  KAFKA_TOPIC: "sale_rossman_store"
  SALES_TABLE_NAME: "rossman_sales"
  FORECAST_TABLE_NAME: "forecast_results"
  MLFLOW_ARTIFACT_ROOT: "/storage/mlruns/" # when working on-cloud, you must change this to object storage path like gs://<bucket>/<path>, or if you just wanna try out, create a cluster with only 1 node would do
  AIRFLOW_UID: "501"
  AIRFLOW_PROJ_DIR: "./services/airflow"
  SPARK_STREAM_CHECKPOINTS_PATH: "/opt/airflow/spark_streaming_checkpoints"
  MAIN_DB_PW: "SuperSecurePwdHere"  # Important: Consider using Kubernetes Secrets for this in real use case
